import { getShareToken, getTrackersSnapshot } from '../firebase/firestore.js'
import { TrackerCard } from '../components/TrackerCard.js'
import { store } from '../store/appStore.js'
import { formatDate, formatTTL } from '../utils/date.js'

export async function SharedViewPage(token) {
  const el = document.createElement('div')
  el.className = 'shared-view page-enter'

  el.innerHTML = `
    <div class="container container--narrow">
      <div style="display:flex;align-items:center;justify-content:center;padding:80px 0;">
        <div class="spinner spinner--lg"></div>
      </div>
    </div>
  `

  try {
    // Validate token
    const link = await getShareToken(token)

    if (!link) {
      renderExpired(el, 'This link does not exist.')
      return el
    }

    const expiresAt = link.expiresAt?.toDate ? link.expiresAt.toDate() : new Date(link.expiresAt)
    const isExpired = link.isRevoked || new Date() > expiresAt

    if (isExpired) {
      renderExpired(el, 'This link has expired.')
      return el
    }

    // Fetch tracker data
    const trackers = await getTrackersSnapshot(link.uid, link.mode)
    const ttl      = formatTTL(link.expiresAt)
    const modeStr  = link.mode === 'work' ? 'Work Efficiency' : 'Personal Development'

    el.innerHTML = `
      <div class="container container--narrow">
        <div class="shared-header">
          <div class="shared-brand">Quotient — Proof of Work</div>
          <div class="shared-title">${modeStr} Dashboard</div>
          <div class="shared-meta">
            Read-only snapshot · ${ttl}
          </div>
        </div>

        <div class="section-label" style="margin-bottom:var(--space-4);">
          ${trackers.length} Tracker${trackers.length !== 1 ? 's' : ''}
        </div>

        ${trackers.length
          ? `<div class="tracker-grid" id="shared-grid"></div>`
          : `<div class="empty-state">
               <div class="empty-state__title">No trackers shared</div>
               <div class="empty-state__sub">This dashboard has no trackers in ${link.mode} mode.</div>
             </div>`
        }

        <div style="margin-top:var(--space-16);padding-top:var(--space-8);border-top:1px solid var(--border-default);text-align:center;">
          <div style="font-size:var(--text-xs);color:var(--text-tertiary);letter-spacing:0.08em;text-transform:uppercase;">
            Generated by Quotient · ${formatDate(new Date().toISOString())}
          </div>
        </div>
      </div>
    `

    // Override store mode temporarily so TrackerCard renders correctly
    const prevMode = store.get('mode')
    store.set('mode', link.mode)

    const grid = el.querySelector('#shared-grid')
    if (grid) {
      trackers.forEach(tracker => {
        const card = TrackerCard(tracker)
        // Disable all interactive elements in the card (read-only)
        card.style.pointerEvents = 'none'
        card.style.cursor = 'default'
        grid.appendChild(card)
      })
    }

    // Restore store mode
    store.set('mode', prevMode)

  } catch (e) {
    console.error(e)
    renderExpired(el, 'Unable to load this shared view.')
  }

  return el
}

function renderExpired(el, message) {
  el.innerHTML = `
    <div class="expired-state">
      <div style="display:flex;flex-direction:column;align-items:center;gap:var(--space-5);text-align:center;">
        <div style="font-size:var(--text-xs);font-weight:600;letter-spacing:0.12em;text-transform:uppercase;color:var(--text-tertiary);">
          Quotient
        </div>
        <div style="font-size:var(--text-2xl);font-weight:700;letter-spacing:-0.02em;color:var(--text-primary);">
          ${message}
        </div>
        <div style="font-size:var(--text-base);color:var(--text-tertiary);max-width:280px;line-height:1.6;">
          Quotient share links expire 6 hours after creation for security.
        </div>
        <a href="/" style="margin-top:var(--space-4);">
          <button class="btn btn--ghost">Back to Quotient</button>
        </a>
      </div>
    </div>
  `
}
